services:
  frontend:
    build: .
    container_name: task-movil-app
    ports:
      - "8001:8001"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
