pipeline {
    agent any

    stages {
        stage('Clonar código') {
            steps {
                git branch: 'main', url: 'https://github.com/camilo28k/task-movil-app.git'
            }
        }

        stage('Instalar dependencias') {
            steps {
                sh 'npm install'
            }
        }

        stage('Construir aplicación') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Construir imagen Docker') {
            steps {
                sh 'docker build -t task-movil-app .'
            }
        }

        stage('Desplegar contenedor') {
            steps {
                sh 'docker compose down || true'
                sh 'docker compose up -d'
            }
        }
    }

    post {
        success {
            echo '✅ Despliegue exitoso de task-movil-app en Docker (Puerto 8080:9000).'
        }
        failure {
            echo '⚠️ Error en el pipeline del frontend. Revisa logs en Jenkins.'
        }
    }
}
